# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Elaine's Fieldnotes
tagline: Pretty pictures and shiny things
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello! I'm Elaine, a 4th year Computer Science student at the University 
  of Waterloo. I love discovering how and why things work. These pages documents 
  some of my thoughts and learnings as I go. Enjoy your stay here and have a lovely day!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

author: 
  name: Elaine Zhong
  url: https://github.com/Chrezon
  avatar: https://avatars.githubusercontent.com/u/40221885

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme
remote_theme: vfvong/jekyll-theme-tao
theme: jekyll-theme-tao

categories_path: /
# tags_path: /tags/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
